### ISSUE TITLE
Failed to use in Bamboo

### ISSUE THREAD

**Issue by Dr-Dream** [johnthagen/cppcheck-junit#1]
If no error in cppcheck no JUnit file generated.
So in that case bamboo JUnit parser marks build as failed.
Probably it is better to create "pseudo" testsuite which is marked as successfull?

**Comment by johnthagen** [comment]
@Dr-Dream Please try out version `1.1.1` and see if it meets your needs.

**Comment by Dr-Dream** [comment]
Great work!
1.1.1 Works well.
Many Thanks!
