### ISSUE TITLE
Drop Python 3.6

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/cppcheck-junit#18]
Python 3.6 is EOL and support should be dropped.

@PfannenHans since you are a recent contributor, I wanted to check with you first that you do not need Python 3.6 support with your new feature.

**Comment by PfannenHans** [comment]
Thanks for asking. As far as i am concerned everything is using python 3.8 or 3.9.

**Comment by johnthagen** [comment]
Closed in [b9b6623](https://github.com/johnthagen/cppcheck-junit/commit/b9b6623c7ceeddc9dfd15ab9d049003eb78207f4)
