### ISSUE TITLE
Script failure on errors without location

### ISSUE THREAD

**Issue by Dr-Dream** [johnthagen/cppcheck-junit#2]
In case if cppcheck report contains error without 'location' tag (for example 'missingIncludes') script fails.

**Comment by johnthagen** [comment]
@Dr-Dream Can you please provide an example that reproduces this failure?

Please provide:
- Cppcheck version
- Example C++ source file that triggers the condition
- Exact run steps that trigger the behaviour.

Thanks.

**Comment by Dr-Dream** [comment]
cppchek 1.73
I've tried with different options, so i've attached with last result. It's no an missingIncludes, but 'toomanyconfigs'.
Runnin command
`cppcheck --xml-version=2 --enable=warning . 2>cppcheck-result.xml`
`cppcheck_junit cppcheck-result.xml cppcheck-junit.xml`

Result is here 
https://github.com/Dr-Dream/examples/blob/master/cppcheck-junit-tests/cppcheck-result.xml

I'm not sure i could provide you a sample code in short time, because it's not mine actually, but my employer.
I'll try to prepare something simmilar in short time.

PS:also tested on 1.1.1

**Comment by johnthagen** [comment]
@Dr-Dream Thanks for the test file.  Please try out version `1.1.2` to confirm your issue is resolved.

**Comment by mjcaisse** [comment]
This still seems to be a problem. For example, the following output for cppcheck is causing problems with HEAD on master:

`<?xml version="1.0" encoding="UTF-8"?>
<results version="2">
  <cppcheck version="1.61"/>
  <errors>
  <error id="missingInclude" severity="information" msg="Cppcheck cannot find all the include files (use --check-config for details)" verbose="Cppcheck cannot find all the include files. Cppcheck can check the code without t
he include files found. But the results will probably be more accurate if all the include files are found. Please check your project's include directories and add all of them as include directories for Cppcheck. To see what 
files Cppcheck cannot find use --check-config.">
  </error>
  </errors>
</results>
`

**Comment by johnthagen** [comment]
@mjcaisse Could you provide an example `.cpp` file that produces this output?  I'd like to run the latest Cppcheck (1.7.4 as of writing) against it to make a good unit test for this to make sure this doesn't pop up again in the future.

**Comment by johnthagen** [comment]
@mjcaisse Thanks for issue report and the PR!  Please test if `cppcheck-junit` 1.2.0 has corrected your problem.
