### ISSUE TITLE
Failing tests not showing up on bamboo.

### ISSUE THREAD

**Issue by bjornpiltz** [johnthagen/cppcheck-junit#5]
I have added the following steps to my bamboo plan

- `cppcheck ... 2> cppcheck-result.xml`
- `cppcheck_junit cppcheck-result.xml cppcheck-junit.xml`
- JUnit Parser

I can see a passing test on the dashboard if cppcheck reports no errrors. If there are errors, however, I can only see that JUnit parser failed. No further information is available. 

Here are my logs:

```bash
build	16-Oct-2017 10:21:36	Running cppcheck:
cppcheck --xml --xml-version=2 --enable=all --
project=compile_commands.json 2> cppcheck-result.xml
```
### cppcheck-result.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
	<results version="2">
		<cppcheck version="1.80"/>
		<errors>
			<error id="missingInclude" severity="information" msg="Cppcheck cannot find all the include files (use --check-config for details)" verbose="Cppcheck cannot find all the include files. Cppcheck can check the code without the include files found. But the results will probably be more accurate if all the include files are found. Please check your project&apos;s include directories and add all of them as include directories for Cppcheck. To see what files Cppcheck cannot find use --check-config."/>
		</errors>
	</results>
```

```
build	16-Oct-2017 10:21:36	Running cppcheck_junit:
cppcheck_junit cppcheck-result.xml cppcheck-junit.xml
```
### cppcheck-junit.xml:
```xml
<?xml version='1.0' encoding='utf-8'?>
	<testsuite errors="1" failures="0" hostname="XXX" name="Cppcheck errors" tests="1" time="1" timestamp="2017-10-16T10:21:36.514058">
		<testcase classname="" name="" time="1">
			<error file="" line="0" message="0: (information) Cppcheck cannot find all the include files (use --check-config for details)" type="" />
	</testcase>
</testsuite>
```

```
simple	16-Oct-2017 10:21:36	Finished task 'cppcheck' with result: Success
simple	16-Oct-2017 10:21:36	Starting task 'JUnit Parser' of type 'com.atlassian.bamboo.plugins.testresultparser:task.testresultparser.junit'
simple	16-Oct-2017 10:21:36	Parsing test results under <path>
simple	16-Oct-2017 10:21:36	Failing task since 1 failing test cases were found.
simple	16-Oct-2017 10:21:36	Finished task 'JUnit Parser' with result: Failed
```

**Comment by johnthagen** [comment]
What version of `cppcheck-junit` are you running and under what Python version?

**Comment by bjornpiltz** [comment]
Thanks for your quick response!

cppcheck-junit==1.4.0
Python 2.7.5

**Comment by johnthagen** [comment]
Could you try with version 1.3.0 and 1.1.1 and see if either of those work? I'm wondering if #4 broke Bamboo.

**Comment by bjornpiltz** [comment]
# v1.1.1
Crashes :(
```bash
$ wget https://github.com/johnthagen/cppcheck-junit/archive/v1.1.1.tar.gz
$ tar xvfz v1.1.1.tar.gz
$ python  cppcheck-junit-1.1.1/cppcheck_junit.py input.xml output.xml
Traceback (most recent call last):
  File "cppcheck-junit-1.1.1/cppcheck_junit.py", line 170, in <module>
    sys.exit(main())
  File "cppcheck-junit-1.1.1/cppcheck_junit.py", line 149, in main
    errors = parse_cppcheck(args.input_file)
  File "cppcheck-junit-1.1.1/cppcheck_junit.py", line 83, in parse_cppcheck
    error = CppcheckError(file=location_element.get('file'),
AttributeError: 'NoneType' object has no attribute 'get'

```

# v1.3.0
Output is slightly different, but bamboo still doesn't pick it up.
```bash
$ wget https://github.com/johnthagen/cppcheck-junit/archive/v1.3.0.tar.gz
$ tar xvfz v1.3.0.tar.gz
$ python cppcheck-junit-1.3.0/cppcheck_junit.py cppcheck-result.xml cppcheck-junit.xml
```
### cppcheck-junit.xml:
```xml
<?xml version='1.0' encoding='utf-8'?>
<testsuite errors="1" failures="0" name="Cppcheck errors" tests="1" time="1">
	<testcase name="">
		<error file="" line="0" message="0: (information) Cppcheck cannot find all the include files (use --check-config for details)" />
	</testcase>
</testsuite>
```

**Comment by johnthagen** [comment]
I don't have access to a Bamboo server, so I'm not sure how to resolve this. If you can find a output that Bamboo does parse and one that it doesn't, then we can try to compare them and see what is wrong.

Might also want to double check the file name and the regex Bamboo is using to pick up the JUnit files.

For historical sake, what version of Bamboo are you running?

**Comment by bjornpiltz** [comment]
I'm using the latest version of Bamboo - 6.1.1. I know the regex is ok, since I get a passed test when the xml file contains no error.

The problem is that Bamboo's JUnit Parser provides no feedback as to why it objects to the xml file. I'll try to report it to them and see what they say.

Thanks for looking in to this!

**Comment by bjornpiltz** [comment]
Ok, I've got it. As mentioned [here](https://jira.atlassian.com/browse/BAM-18510?_ga=2.160280254.240826769.1508251419-2118099472.1506500640) and [here](https://community.atlassian.com/t5/Bamboo-questions/Does-JUnit-Parser-require-the-classname-and-name-attributes-to/qaq-p/229732), `name` and `classname` can't be empty. 

The following workaround fixes it for me:

```bash
sed -i 's/classname=""/classname="foo"/g' cppcheck-junit.xml
sed -i 's/name=""/name="bar"/g' cppcheck-junit.xml
```

**Comment by johnthagen** [comment]
Thanks for the information. I'll look into fixing this later today.

@yamokosk @mjcaisse Could you comment on if filling these in with non-empty strings would be an issue for your use case?

**Comment by johnthagen** [comment]
@bjornpiltz Could you confirm that #6 fixes your issue?

**Comment by johnthagen** [comment]
@bjornpiltz Please test that [1.5.0](https://pypi.python.org/pypi/cppcheck-junit/1.5.0) fixes your issue.

**Comment by bjornpiltz** [comment]
It does.
